version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
      - proxy_manager

  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_BACKEND_URL=https://truth.chickenkiller.com/api

  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=postgresql://app:oXROms9Cie4E@ep-plain-leaf-a4b9ragz-pooler.us-east-1.aws.neon.tech:5432/verceldb

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: oXROms9Cie4E
      POSTGRES_DB: verceldb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  proxy_manager:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "8090:81"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  postgres_data:
